name: "Michael's Blog"
favicon: null
layout_spectrum: 0.94184
typography_spectrum: 0.6517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f7f6'
    - '#237ae4'
    - '#46b8fe'
    - '#5f7812'
    - '#153855'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
